Billboard app
MostDeadDeveloper/Automated-Classroom-Assistance-System-with-Integrations pull request #4
Opened 2021-06-28 14:29 UTC by Salvoid

Competed:
Models, Forms, Views, and Basic HTML and CSS
TO-DO:
Clean Up HTML and CSS

2021-06-28 14:42 UTC, MostDeadDeveloper reviewed
Apply All Changes Indicated Here.

2021-06-28 14:42 UTC, MostDeadDeveloper commented on Testfile.txt
> +Test Change.
Remove this file

2021-06-28 14:42 UTC, MostDeadDeveloper commented on app/account/migrations/0003_alter_account_first_name.py
> +# Generated by Django 3.2.4 on 2021-06-27 12:57
No Need to Include Migrations in this MR.

2021-06-28 14:42 UTC, MostDeadDeveloper commented on app/app/urls.py
> +    path('billboard/', include('billboard.urls')),
Add  the billboard app in the top, not the lowest. 

The base redirect view must always be the last url.

2021-06-28 14:42 UTC, MostDeadDeveloper commented on app/billboard/forms.py
> +        widgets = {'professor_data': forms.TextInput(attrs={'size': 50}),
Consider following PEP8 Standards.

2021-06-28 14:42 UTC, MostDeadDeveloper commented on app/billboard/migrations/0001_initial.py
> +# Generated by Django 3.2.4 on 2021-06-28 13:01
Remove This migration, you don't need to include it in this MR

2021-06-28 14:42 UTC, MostDeadDeveloper commented on app/billboard/models.py
> +        self.up_dates = timezone.now()
up_date or up_dates?

2021-06-28 14:42 UTC, MostDeadDeveloper commented on app/billboard/templates/billboard/_base_view.html
> +        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" cross
Put this in header.html if it doesn't exist already.

2021-06-28 14:42 UTC, MostDeadDeveloper commented on app/billboard/templates/billboard/base_view.html
> +        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" cross
Put this in header.html if it doesn't exist already. (1)

2021-06-28 14:42 UTC, MostDeadDeveloper commented on app/billboard/templates/billboard/icons/file-earmark-plus.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-file-earmark-plus" viewBox="0 0 16 16">
This should be in the assets folder.

2021-06-28 14:42 UTC, MostDeadDeveloper commented on app/billboard/templates/billboard/icons/pencil-fill.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-fill" viewBox="0 0 16 16">
This should be in the assets folder. (1)

2021-06-28 14:42 UTC, MostDeadDeveloper commented on app/billboard/templates/billboard/_base_view.html
> +{% load static %}
Use the default base.html of our project.

2021-06-28 14:42 UTC, MostDeadDeveloper commented on app/billboard/views.py
> +from django.shortcuts import render, redirect, get_object_or_404
I prefer to use the Class Based Views, if possible. 

But if it will take too much time, just ignore this.

2021-06-28 14:42 UTC, MostDeadDeveloper commented on app/subject/migrations/0001_initial.py
> +# Generated by Django 3.2.4 on 2021-06-27 12:57
Remove this migration.

2021-06-28 14:43 UTC, MostDeadDeveloper requested changes
Remove all PyCache Files, its just cache from running the server. It's not needed.

2021-06-28 14:46 UTC, MostDeadDeveloper commented
For Developers, You can use git add <file> to specify only changes you want to add.

2021-06-29 14:41 UTC, Salvoid commented
TO DO: (Done/Finished: *)[06-29-2021]

Requests:
*-url billboard app add to top
	app/url.py
*-follow PEP8 Standards
	forms.py
*-remove all migration folders
-use class based views(if possible)
	views.py
*-transfer svg to assets folder
*-put links to header.html
*-put links to header.html(1)
*-remove
	Testfile.txt
*use the default base.html

Additional Changes:
*-added feature to delete a professor and their information

2021-06-30 08:29 UTC, MostDeadDeveloper approved these changes

2021-06-30 08:29 UTC, MostDeadDeveloper commented on app/account/migrations/0001_initial.py
> -# Generated by Django 2.2.18 on 2021-05-20 09:17
don't remove the existing migrations.

2021-06-30 08:30 UTC, merged